### ISSUE TITLE
Difference in SAKT's slicing operation

### ISSUE THREAD

**Issue by aporia3517** [THUwangcy/HawkesKT#1]
Hi @THUwangcy, thanks for sharing your work.

While all other models use [1:] slicing to make predictions and labels,
https://github.com/THUwangcy/HawkesKT/blob/e1710686508f913758f02b55341d9739024a819a/src/models/AKT.py#L89
SAKT uses [:-1] slicing for prediction. Can you tell me the difference?

https://github.com/THUwangcy/HawkesKT/blob/e1710686508f913758f02b55341d9739024a819a/src/models/SAKT.py#L59

**Comment by THUwangcy** [comment]
To my understanding, the original paper of SAKT uses the output at t-1 step to predict the correctness at t step to avoid label leakage (the input at t step includes the label information). While for AKT, there are special designs to make the model only aware of the question id at t step rather than the correctness.

**Comment by aporia3517** [comment]
Thanks for the reply!
